# Playbook that Collects DKPG Log from the Control to Managed Node

- hosts: all
  become: true
  tasks:

  - name: Create a directory to store log files
    ansible.builtin.file:
      path: /logfiles
      state: directory

  - name: Copy dpkg log file from control node to managed node
    ansible.builtin.shell:
      cmd: "cp -r /var/log/ /logfiles/"
    register: result

  - name: Display Output
    debug:
      var: result.stdout
